### ISSUE TITLE
Don't forget to add trailing '/' 

### ISSUE THREAD

**Issue by dfermin** [brockpalen/archivetar#15]
Hi

This is not really a bug so much as a feature request.

If you issue the command:

```
archivetar --prefix myPrefix --lz4 --save-purge-list --size 1G --tar-size 300G \
--destination globus#remote \
--destination-dir /nfs/dataden/parent_dir/target_dir
```

The contents of the folder you are in are copied to `/nfs/dataden/parent_dir` not `/nfs/dataden/parent_dir/target_dir`. 
You _must_ include the trailing `/` slash at the end like this: `--destination-dir /nfs/dataden/parent_dir/target_dir/` so that archivetar creates the final destination directory.

Again this really isn't a bug it's more of a feature request.

**Comment by brockpalen** [comment]
Thanks @dfermin   this is fixed in v0.10.1
