### ISSUE TITLE
Requesting the option to turn off or limit Globus emails

### ISSUE THREAD

**Issue by jhschwartz** [brockpalen/archivetar#26]
Right now I'm using architetar to archive a ~25 terabyte dataset. It's working great but my inbox is getting flooded with 250 Globus "transfer success" emails. It would be nice to either turn off notifications or to get a summary email of the entire transfer. Clearly not a mission-critical feature but thought I should mention it anyway! Thanks.

**Comment by brockpalen** [comment]
This is added with v0.15.4 and later `--no-notify-on-succeeded` and several other options for controlling globus notifications and behavior on different errors.
