### ISSUE TITLE
dwalk invalid options

### ISSUE THREAD

**Issue by xk42** [brockpalen/archivetar#45]
I'm getting dwalk invalid options when I'm testing archivetar with the command `archivetar  --prefix anew`

From what I can see, dwalk is adding some flags that does not exists.

```
/nfs/sw/mpiFileUtils/install//bin/dwalk: unrecognized option '--type'
/nfs/sw/mpiFileUtils/install//bin/dwalk: unrecognized option '--size'
/nfs/sw/mpiFileUtils/install//bin/dwalk: invalid option -- '1'
/nfs/sw/mpiFileUtils/install//bin/dwalk: invalid option -- '0'
```
```
ERROR:root:Problem running: ['/usr/lib64/openmpi/bin/mpirun', '--oversubscribe', '-np', '12', '/nfs/sw/mpiFileUtils/install//bin/dwalk', '--sort', 'name', '--type', 'f', '--size', '-1000000000000000000', '--progress', '10', '--input', '/scratch/anew-2024-03-01-16-01-28.cache', '--text-output', '/scratch/anew-2024-03-01-16-01-28.under.txt', '--output', '/scratch/anew-2024-03-01-16-01-28.under.cache'] and Command '['/usr/lib64/openmpi/bin/mpirun', '--oversubscribe', '-np', '12', '/nfs/sw/mpiFileUtils/install//bin/dwalk', '--sort', 'name', '--type', 'f', '--size', '-1000000000000000000', '--progress', '10', '--input', '/scratch/anew-2024-03-01-16-01-28.cache', '--text-output', '/scratch/anew-2024-03-01-16-01-28.under.txt', '--output', '/scratch/anew-2024-03-01-16-01-28.under.cache']' returned non-zero exit status 1.
```

**Comment by brockpalen** [comment]
Are you using the current version of mpiFileUtils?  archivetar depends on a patched older version where options from `dfind` were ported over to `dwalk`.

If you are look in `build.sh`  where it pulls the patched version from my repo.

**Comment by xk42** [comment]
> Are you using the current version of mpiFileUtils? archivetar depends on a patched older version where options from `dfind` were ported over to `dwalk`.
> 
> If you are look in `build.sh` where it pulls the patched version from my repo.

Ah thanks for the prompt reply. Yes I was using the current version. I'll try the patched version.

The git link to the mpifileutils is incorrect https://github.com/brockpalen/archivetar/blob/master/INSTALL.md#requirements
Whereas the one in build.sh is fine. I'll give that a go now.
