### ISSUE TITLE
multiprocess.cpu_count()  doesn't account for cgroup limits set by HPC Scheds

### ISSUE THREAD

**Issue by brockpalen** [brockpalen/archivetar#8]
Currently default number of tar processes is set to `multiprocess.cpu_count() / 4` 

This appears to not be cgroup / cpuset aware and still returns total cores physical in the system not what is usable by the process.

```
srun --pty --account=support --ntasks-per-node=1 --cpus-per-task=16 --mem-per-cpu=5G --nodes=1  /bin/bash 

python3
>>> import multiprocessing as mp
>>> mp.cpu_count()
36

hwloc-calc --intersect PU $(hwloc-bind --get)
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
```

**Comment by brockpalen** [comment]
There is an hwloc python module, but appears unmaintained, an option would be to check ENV for common scheduler variables:

```
SLURM_CPUS_PER_TASK=16
etc.
```

But this is not dynamic for other environments,

**Comment by prehensilecode** [comment]
This is an old issue with `multiprocessing` that its authors won't fix: https://bugs.python.org/issue26692 (migrated to github https://github.com/python/cpython/issues/70879 )
